# --- CONEXAO COM NEON (NUVEM) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- CONFIGURACOES DO DRIVER ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cria as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# --- BOAS PRATICAS ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true