# CONFIGURACAO BANCO LOCAL DEV 
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_local
spring.datasource.username=postgres
spring.datasource.password=123456

# Mostra o SQL no console 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CRIA as tabelas automaticamente 
spring.jpa.hibernate.ddl-auto=update

# Dialeto 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect